### PR TITLE
Fix import cluster issue with forced flag:

### LINKED ISSUE #432: Can not import a cluster with terraform-provider-rke V1.4.3.
Terraform: v1.5.0
RKE Terraform Provider: v1.4.3
RKE Cluster: v1.26.9-rancher1-1
RKE: 1.4.7

When importing a cluster using latest 1.4.3 version of the provider getting following error : 
`Error:
│ ============= RKE outputs ==============
│ time="2023-11-23T15:27:29+02:00" level=info msg="Creating RKE cluster..."
│
│ kubernetes version v1.26.9-rancher1-1 requires enable_cri_dockerd to be set to true`

Although is set: `enable_cri_dockerd: true`

How to reproduce:
Use a `cluster.yaml` file and a `cluster.rkestate` file for a running cluster created from RKE CLI.
At the `cluster.yaml` set the `enable_cri_dockerd: true`.

Import cluster using `terraform-provider-rke`:

`terraform import rke_cluster.qa  cluster.yml:cluster.rkestate`.

Import will fail, even if `enable_cri_dockerd` is properly set to `true`

### PR DESCRIPTION
**Pull request by leftyb**
Issue: #432

enable_cri_dockerd =  true

## Problem
Issue when importing a cluster. Fails with message:
`kubernetes version ..... requires enable_cri_dockerd to be set to true`
enable_cri_dockerd  flas always set to the default value `false`
## Solution
Use the value set at the cluster.yaml file.
Use default only if not set at the cluster.yaml file

## Testing
Tested importing a cluster and setting the value to true

### Manual Testing
Tested importing a cluster and setting the value to true

### Automated Testing
Added latest K8s version at the automated test.

### CODE REVIEW

**Comment by LefterisBanos** [comment]
@jiaqiluo Tested importing and all worked:

`terraform` import rke_cluster.qa  ../cluster.yml:../cluster.rkestate
Acquiring state lock. This may take a few moments...
rke_cluster.qa: Importing from ID "../cluster.yml:../cluster.rkestate"...
rke_cluster.qa: Import prepared!
  Prepared rke for import
rke_cluster.qa: Refreshing state... [id=...-...-...]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Releasing state lock. This may take a few moments...`

**Comment by li-il-li** [comment]
We merged this and used it to import our Prod cluster state back into terraform! It does what it say and saved our day(s). Thanks a lot!

File: rke/structure_rke_cluster.go [hunk 1]
```diff
@@ -293,11 +293,11 @@ func expandRKECluster(in *schema.ResourceData) (string, *rancher.RancherKubernet
 		obj.DNS = expandRKEClusterDNS(v)
 	}
 
-	if v, ok := in.Get("enable_cri_dockerd").(bool); ok {
+	if v, ok := in.Get("enable_cri_dockerd").(bool); ok && obj.EnableCRIDockerd == nil {
```
Comment (jiaqiluo) [inline rke/structure_rke_cluster.go:296]: Note to other reviewers:  
In the case of importing an RKE cluster, we define an empty rke_cluster resource in the terraform configuration file:
```
resource "rke_cluster" "test1" {
  # (resource arguments)
}
```
The value for `enable_cri_dockerd` is read from the provided cluster.yml file,  not specified in the above rke_clutster resource.  Therefore, the value should not be overwritten if it is not nil. 

The same rule is applied to the `ignore_docker_version` field  below.

**Review by jiaqiluo — APPROVED** [review]
LGTM.
We need one more approval from the team to merge the PR.

**Review by jakefhyde — APPROVED** [review]
